create table if not exists pets (
    id text primary key,
    name text not null check (char_length(name) between 1 and 20),
    state text not null check (state in ('normal', 'sick', 'evolved')),
    hunger integer not null check (hunger between 0 and 100),
    happiness integer not null check (happiness between 0 and 100),
    energy integer not null check (energy between 0 and 100),
    age_ticks integer not null default 0 check (age_ticks >= 0),
    is_evolved boolean not null default false,
    evolved_at timestamptz,
    last_tick_at timestamptz not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    sick_streak integer not null default 0 check (sick_streak >= 0),
    recovery_streak integer not null default 0 check (recovery_streak >= 0),
    care_action_count integer not null default 0 check (care_action_count >= 0)
);

create table if not exists pet_events (
    id bigint generated by default as identity primary key,
    pet_id text not null references pets(id) on delete cascade,
    event_type text not null check (
        event_type in (
            'action',
            'became_sick',
            'recovered',
            'evolved',
            'time_anomaly'
        )
    ),
    event_message text not null,
    action text check (action in ('feed', 'play', 'rest') or action is null),
    payload_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null
);

create index if not exists pet_events_pet_created_idx
    on pet_events (pet_id, created_at desc);
